#!/usr/bin/env sh

if [ -z "${DOCKER_TAG}" ]; then
  docker build --build-arg=COMMIT=$(git rev-parse HEAD) --build-arg=BRANCH=$(git rev-parse --abbrev-ref HEAD) -t $IMAGE_NAME .
else
  docker build --build-arg=COMMIT=$(git rev-parse HEAD) --build-arg=BRANCH=${DOCKER_TAG} -t $IMAGE_NAME .
fi